config/routes.rb
Harbor::Application.routes.draw do

  root :to => "fleet#show"
  match "/fleet" => "fleet#show", :as => :fleet
  resource :account, :controller => "users"
  resources :users
  resource :user_session
  match "/logout" => "user_sessions#destroy", :as => :logout
end

app/models/notifier.rb
class Notifier < ActionMailer::Base
  default_url_options[:host] = "digitalharborapp.com"
  
  def password_reset_instructions(user)
    subject       "Password Reset Instructions"
    from          "Digital Harbor Auto E-mail  <donabrams+digitalHarborAuto@gmail.com>"
    recipients    user.email
    sent_on       Time.now
    body          :edit_password_reset_url => edit_password_reset_url(user.perishable_token)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.record
    end
    
    def require_user
      unless current_user
        store_location
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      if current_user
        store_location
        redirect_to account_url
        return false
      end
    end
    
    def store_location
      session[:return_to] = request.url
    end
    
    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
end

app/controllers/fleet_controller.rb
class FleetController < ApplicationController
  before_filter :require_user
  helper :all
  def show
    @teacher = current_user.login
    render :layout => false
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_filter :load_user_using_perishable_token, :only => [:edit, :update]
  before_filter :require_no_user
  
  def new
    render
  end
  
  def create
    @user = User.find_by_email(params[:email])
    if @user
      @user.deliver_password_reset_instructions!
      redirect_to root_url
    else
      render :action => :new
    end
  end
  
  def edit
    render
  end

  def update
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.save
      redirect_to account_url
    else
      render :action => :edit
    end
  end

  private
    def load_user_using_perishable_token
      @user = User.find_using_perishable_token(params[:id])
      unless @user
        redirect_to root_url
      end
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
  
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_back_or_default account_url
    else
      render :action => :new
    end
  end
  
  def destroy
    current_user_session.destroy
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_back_or_default account_url
    else
      render :action => :new
    end
  end
  
  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end
  
  def update
    @user = @current_user
    if @user.update_attributes(params[:user])
      redirect_to account_url
    else
      render :action => :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fleet/show.html.erb
<!doctype html>
<html>
<head>
	<title>Digital Harbor</title>
  <link rel="stylesheet" type="text/css" href="reset.css">
  <script type="text/javascript" src="http://use.typekit.com/yua2vns.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <link href="bridge.css" rel="stylesheet" type="text/css"/>
	<script src="/jquery-1.7.min.js"></script>
  <script src="/jquery.fittext.js"></script>
	<script src="/jquery.hint.js"></script>
	<script src="/cloudmine.js"></script>
	<script type="simple/template" id="builderEntity">
		<article>
			<header>
				<h3>${url}</h3>
			</header>
			<nav>
				<button class="eyesOn">Eye</button>
				<button class="delete">Remove</button>
			</nav>
			<aside style='background: url("http://img.bitpixels.com/getthumbnail?code=66924&size=200&url=${url}")'>
			</aside>
		</article>
	</script>
	<script>
	  teacher = "<%= @teacher %>";
	</script>
	<script src="/bridge.js"></script>
	<script src="/application.js"></script>
</head>
<body>
	<header>
		<h1>Digital Harbor</h1>
		<p><%= link_to "Logout", logout_path %></p>
	</header>
	<section id="builder">
	  <h2>What would you<br/> like to teach today ?</h2>
		<form target="#">
			<input type="text" id="newUrl" title="ENTER SITE URL"/>
		</form>
		<ul>
		</ul>
	</section>
	<footer>
		<p>Concept and Project Leader - Andrew Coy</p>
		<p>Site design - Ronin Wood</p>
		<p>Web Developer - Donald Abrams</p>
		<p>iOS Developer - Jonathan Julian and Friends of the Web</p>
		<p>Background photography by SenshiStick</p>
		<p>Creative Commons Attribution-Share Alike 3.0 License</p>
		<p><a href='http://www.bitpixels.com/'>Website thumbnails provided by BitPixels</a></p>
	</footer>
</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Digital Harbor
    =stylesheet_link_tag    "/reset"
    %script{:src=>"http://use.typekit.com/yua2vns.js"}
    :javascript
      try{Typekit.load();}catch(e){}
    %script{:src=>"/jquery-1.7.min.js"}
    %script{:src=>"/jquery.hint.js"}
    %script{:src=>"/jquery.fittext.js"}
    =stylesheet_link_tag    "/bridge"
    %script{:src=>"/application.js"}
    =csrf_meta_tags
%body
  %header
    %h1 Digital Harbor
    -if @current_user
      %p= link_to "Logout", logout_path
  %section#content  
    =yield

app/views/notifier/password_reset_instructions.erb
A request to reset your password has been made. If you did not make this request, simply ignore this email. If you did make this request just click the link below:

<%= @edit_password_reset_url %>

If the above URL does not work try copying and pasting it into your browser. If you continue to have problem please feel free to contact us.

app/views/password_resets/edit.html.haml
%h1 Change My Password
=form_for @user, :url => password_reset_path, :method => :put do |f|
  -if @user.errors
    %p
      -@user.errors.full_messages.each do |msg|
        %li= msg
  %p
    =f.label :password
  %p
    =f.password_field :password
  %p
    =f.label :password_confirmation
  %p
    =f.password_field :password_confirmation
  %p
    =f.submit "Update my password and log me in"

app/views/password_resets/new.html.haml
%h1 Forgot Password
%p Fill out the form below and instructions to reset your password will be emailed to you:
=form_tag password_resets_path do
  %p
    %label Email:
  %p
    =text_field_tag "email"
  %p
    =submit_tag "Reset my password"

app/views/user_sessions/new.html.haml
%h2
  Get everyone 
  %br/
  on the same page.

=form_for @user_session, :url => user_session_path do |f|
  -if @user_session.errors
    %p
      -@user_session.errors.full_messages.each do |msg|
        %li= msg
  %p
    =f.text_field :login
  %p
    =f.label :login
  %p
    =f.password_field :password
  %p
    =f.label :password
  %p
    =f.check_box :remember_me
    =f.label :remember_me
  %p.login
    =f.submit "Login"
    =link_to "Register for access", new_user_url

app/views/users/_form.html.haml
%p
  = form.text_field :login, :title => 'Login'
%p
  = form.password_field :password
%p
  = form.label :password, form.object.new_record? ? nil : "Change password"
%p
  = form.password_field :password_confirmation
%p
  = form.label :password_confirmation
%p
  = form.text_field :email, :title => "Email"

app/views/users/edit.html.haml
%h2 Edit My Account
=form_for @user, :url => account_path do |f|
  -if @user.errors
    -@user.errors.full_messages.each do |msg|
      %li= msg
  =render :partial => "form", :object => f
  =f.submit "Update"
=link_to "My Profile", account_path

app/views/users/new.html.haml
=form_for @user, :url => account_path do |f|
  -if @user.errors
    -@user.errors.full_messages.each do |msg|
      %li= msg
  =render :partial => "form", :object => f
  =f.submit "Register"

app/views/users/show.html.haml
%p
  %b Login:
  =h @user.login
%p
  %b Email:
  =h @user.email 
%p
  %b Login count:
  =h @user.login_count
%p
  %b Last request at:
  =h @user.last_request_at
%p
  %b Last login at:
  =h @user.last_login_at
%p
  %b Current login at:
  =h @user.current_login_at
%p
  %b Last login ip:
  =h @user.last_login_ip
%p
  %b Current login ip:
  =h @user.current_login_ip
= link_to 'Edit', edit_account_path